/**
 * Regenerates data/sample.js from data/inventory.csv so the demo runs with no
 * fetch and no server — open index.html straight off disk and it works.
 *
 *   node tools/build-sample.js
 */
var fs = require('fs');
var path = require('path');

var csv = fs.readFileSync(path.join(__dirname, '..', 'data', 'inventory.csv'), 'utf8');
var out =
  '/* Generated by tools/build-sample.js — do not edit by hand.\n' +
  '   Source: data/inventory.csv */\n' +
  'window.RESTOCK_SAMPLE = ' + JSON.stringify(csv) + ';\n';

fs.writeFileSync(path.join(__dirname, '..', 'data', 'sample.js'), out, 'utf8');
console.log('Wrote data/sample.js — ' + (csv.trim().split('\n').length - 1) + ' SKUs, ' + out.length + ' bytes.');
